# Generated by Django 3.0.2 on 2020-01-23 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0010_auto_20200105_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencdimens',
            name='corrente_nominal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cable.Disjuntor', verbose_name='Corrente Nominal'),
        ),
        migrations.AlterField(
            model_name='residencdimens',
            name='sessao_condutor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cable.TabelaCondutor', verbose_name='Sessão Transversal do Condutor (mm²)'),
        ),
    ]
