# Generated by Django 3.0.2 on 2020-01-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0014_auto_20200124_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencdimens',
            name='corrente_a',
            field=models.FloatField(blank=True, verbose_name='Corrente (A)'),
        ),
    ]
